# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2nPc5WVAVg-f_gjQfu8y2uIGWeerXA1
"""

def calculate_npv(rate, cash_flows):
    npv = 0
    for t in range(len(cash_flows)):
        npv += cash_flows[t] / (1 + rate) ** t
    return npv


rate = float(input("Please enter the rate in decimal: "))
cashflow = int(input("Please enter the initial investment with a negative sign: "))
cashflow1 = int(input("Please enter the investment Year 1: "))
cashflow2 = int(input("Please enter the investment Year 2: "))
cashflow3 = int(input("Please enter the investment Year 3: "))
cashflow4 = int(input("Please enter the investment Year 4: "))

cash_flows = [cashflow, cashflow1, cashflow2, cashflow3,cashflow4]


npv = calculate_npv(rate, cash_flows)
print(f"Net Present Value (NPV): ${npv:.2f}")